spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


mybatis:
  type-aliases-package: com.cloudstudy.domain
  configuration:
    map-underscore-to-camel-case: true